generator/utils.py, lsprotocol/converters.py, lsprotocol/validators.py, pyproject.toml
picking off quite a few typechecking errors.
Some remarks
- I haven't committed the re-generated code
- when I regenerate, several hooks go missing (the same happens on main)
- perhaps you have a set of manual changes that you apply to the autogenerated code?
- I believe that `enable_recursive_aliases` will soon be mypy default, so that seems a very reasonable thing to include
- I haven't added `py.typed`, or tried to update your github workflow to run mypy
- you'll want to do both of those I think: so that others can take advantage of these types, and so that they don't regress
remaining errors are as follows:
```
lsprotocol/types.py:5136: error: Name "kind" already defined on line 5130  [no-redef]
lsprotocol/types.py:5162: error: Name "kind" already defined on line 5153  [no-redef] …
```
=> Fix some errors detected by `mypy`

generator/lsp.json, generator/utils.py, lsprotocol/_hooks.py, lsprotocol/types.py, noxfile.py
Fixes https://github.com/microsoft/lsprotocol/issues/101
In this PR we relax the type validation on some enums. The LSP spec allows custom values, here we detect the type of the custom value and relax the validation on those properties.
=> Support custom values for enums.

.gitignore, generator/utils.py, lsprotocol/_hooks.py, lsprotocol/types.py, noxfile.py
Closes https://github.com/microsoft/lsprotocol/issues/96
1. Fixes issues reported via `mypy --strict lsprotocol`
2. Adds `py.typed` to the package indicating that the package is typed.
3. Adds `mypy` to the linting step.
=> Fix for issue reported via `mypy`

.github/workflows/version-check.yml, .github/workflows/version_check.py, azure-pipelines/template/static_analysis.yml, pyproject.toml
=> Ensure version matches the year.

generator-plugins/python/utils.py, packages/python/lsprotocol/types.py
This was the old definition (params was composed of two things) the combined type was aliased as `WorkspaceConfigurationParams`:
```json
{
"method": "workspace/configuration",
"result": {
"kind": "array",
"element": {
"kind": "reference",
"name": "LSPAny"
}
},
"messageDirection": "serverToClient",
"params": {
"kind": "and",
"items": [
{
"kind": "reference",
"name": "ConfigurationParams"
},
{
"kind": "reference",
"name": "PartialResultParams"
}
]
},
"documentation": "The 'workspace/configuration' request is sent from the server to the client to fetch a certain\nconfiguration setting.\n\nThis pull model replaces the old push model were the client signaled configuration change via an\nevent. If the server still needs to react to configuration changes (since the server caches the\nresult of …
```
=> Preserve types for backwards compatibility.

packages/python/pyproject.toml
`lsprotocol` uses the `import attrs` API which was only introduced in [`v21.3.0`](https://www.attrs.org/en/stable/changelog.html#id7) .
This PR sets a minimum version for attrs in the python package's `pyproject.toml` to hopefully guard against issues [like this one](https://github.com/swyddfa/esbonio/issues/147#issuecomment-1456102830) in the future.
**Question:** Is it sufficient to rely on the version bound set here to ensure the correct version is also installed for `pygls` and `esbonio`? Or since both downstream packages also `import attrs` themselves, is it more correct to have a version bound set in both `pygls` and `esbonio`? :thinking:
=> Introduce lower bound on `attrs` version

generator-plugins/dotnet/dotnet_special_classes.py, generator-plugins/python/utils.py, generator-plugins/rust/rust_structs.py, generator/lsp.json, packages/python/lsprotocol/types.py, packages/python/lsprotocol/validators.py, packages/rust/lsprotocol/src/lib.rs, tests/python/common/jsonrpc.py, tests/python/test_cattrs_special_cases.py
Closes https://github.com/microsoft/lsprotocol/issues/210
=> LSP update adds new TextDocument InlineCompletion request

.github/workflows/pr-check.yml, packages/python/lsprotocol/_hooks.py, tests/python/requests/test_inlay_hint_resolve_request.py
=> Add structure hook for `Union[str, List[InlayHintLabelPart]]`

generator-plugins/python/utils.py, packages/python/lsprotocol/_hooks.py, packages/python/lsprotocol/types.py, packages/python/pyproject.toml, tests/python/test_cattrs_special_cases.py
Fix https://github.com/microsoft/lsprotocol/issues/228
=> Fix bug with structuring LSPObject type

.devcontainer/devcontainer.json
Adds devcontainer support to the repo for easier use on Codespaces or VS Code remote dev
=> Add devcontainer support to repo

generator/__main__.py
We are finalizing the CLI api for generator. We don't need `--schema` as we don't plan on supporting custom schemas at this point.
=> Remove unused `--schema` switch

generator/plugins/dotnet/custom/OrType.cs, generator/plugins/dotnet/dotnet_classes.py, generator/plugins/dotnet/dotnet_helpers.py, generator/plugins/dotnet/dotnet_special_classes.py
Fixes https://github.com/microsoft/lsprotocol/issues/253
=> Use `record` instead of `class` for LSP types.

packages/python/lsprotocol/_hooks.py, tests/python/test_cattrs_special_cases.py
Fixes https://github.com/microsoft/lsprotocol/issues/259
=> Fix for missing notebook selector hook

generator/lsp.json, packages/python/lsprotocol/types.py, packages/rust/lsprotocol/src/lib.rs
Closes https://github.com/microsoft/lsprotocol/issues/263
=> Update to latest lsp spec

azure-pipelines/release-pypi.yml
In https://dev.azure.com/monacotools/Monaco/_build/results?buildId=229140&view=logs&j=9c6ceecd-5363-56f1-0e78-199c2ab175fa&t=dcca69f2-0e61-5643-f82d-945c312c3de6, we see the download task download the artifact to `$(Build.SourcesDirectory)` directly. It then tries to upload `$(Build.SourcesDirectory)/packages/python/dist` to ESRP later but can't find it. The default packageLocation value is `$(Build.SourcesDirectory)/dist`, which would have found the artifact.
A question I have is where does the download task come from? I don't see any download tasks defined under `vscode-engineering/azure-pipelines/pypi-package`, but I do see one defined under https://github.com/microsoft/lsprotocol/blob/790f259e2019b47431f786d11c9b815441218f0c/azure-pipelines/template/publish_pypi.yml#L14. Is that …
=> Use default package location

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, scripts/onCreateCommand.sh, scripts/postCreateCommand.sh
Dev Container support for lsprotocol repository, referencing #234 and adding more things on the way, such as multiple Python versions, cargo, dotnet, venv, requirements, but in a way similar to how dev container is done in the VS Code Python repo: https://github.com/microsoft/vscode-python/pull/21675
=> Dev Container for lsprotocol

packages/python/lsprotocol/_hooks.py, tests/python/test_cattrs_special_cases.py
Fixes https://github.com/microsoft/lsprotocol/issues/270
=> Add PositionEncodingKind hook

generator/plugins/python/utils.py, packages/python/lsprotocol/_hooks.py, packages/python/lsprotocol/types.py
```
pip install lsprotocol
pip install mypy
```
The `main.py`:
```
from typing import List
from lsprotocol import types
def get_edits() -> List[types.TextEdit]:
return [
types.TextEdit(
types.Range(types.Position(0, 0), types.Position(0, 1)),
'new text'
)
]
edits = get_edits()
types.TextDocumentEdit(
types.OptionalVersionedTextDocumentIdentifier('file', 1),
edits,
)
```
The output of `mypy main.py`:
```
main.py:18: error: Argument 2 to "TextDocumentEdit" has incompatible type "list[TextEdit]"; expected "list[TextEdit | AnnotatedTextEdit]"  [arg-type]
main.py:18: note: "List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
main.py:18: note: Consider using "Sequence" instead, which is covariant
Found 1 error in 1 file (checked 1 source file)
``` …
=> Use Sequence instead of List

generator/plugins/dotnet/custom/OrTypeConverter.cs, generator/plugins/dotnet/custom/Validators.cs, generator/plugins/dotnet/dotnet_classes.py
Closes https://github.com/microsoft/lsprotocol/issues/255
=> Dotnet change `uint` to `long`

packages/python/pyproject.toml, requirements.in
Closes #301.
Will resolve https://github.com/python-lsp/python-lsp-ruff/issues/61
=> Tighten cattrs dependency

packages/python/lsprotocol/_hooks.py, tests/python/requests/test_workspace_symbols_request.py
Closes https://github.com/microsoft/lsprotocol/issues/308
=> Fix bug with `WorkspaceSymbol` structuring hook

generator/model.py, scripts/onCreateCommand.sh
The `:latest` syntax used in the  `pyenv` invokation in `onCreateCommand.sh` does not appear to exist. Because of this, the devcontainer fails to build. The fix is to specify the Python versions without patch versions, which makes `pyenv` automatically use the latest version.
Snippet from the log for the previously failing build:
```
pyenv: version `latest' not installed
pyenv: python3.8: command not found
The `python3.8' command exists in these Python versions:
3.8.18
Note: See 'pyenv help global' for tips on allowing both
python2 and python3 to be found.
scripts/onCreateCommand.sh: line 27: /workspaces/lsprotocol/.venv/bin/activate: No such file or directory
[1268491 ms] onCreateCommand failed with exit code 1. Skipping any further user-provided commands.
```
=> Fixed pyenv version syntax

.github/workflows/dep-bot-auto-merge.yml
This is only so that we don't have to hit merge after approving a dependa-bot version update change.
=> Enable auto merge on dep bot (will require approval)

generator/plugins/python/utils.py, packages/python/lsprotocol/types.py
This makes it possible for cattrs to build a disambiguation function based on this unique field, which allows one to do things like:
```
>>> from lsprotocol import types, converters
>>>
>>> converter = converters.get_converter()
>>> d = {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"Server starting"}}
>>> converter.structure(d, types.NOTIFICATIONS | types.REQUESTS)
WindowLogMessageNotification(params=LogMessageParams(type=<MessageType.Info: 3>, message='Server starting'), method='window/logMessage', jsonrpc='2.0')
```
=> [python] Make the method fields of requests, responses and notifications literals

generator/plugins/python/utils.py, packages/python/lsprotocol/_hooks.py, packages/python/lsprotocol/types.py
Fixes https://github.com/microsoft/lsprotocol/issues/344
=> Add customization to CompletionItemKind

generator/plugins/rust/rust_commons.py, generator/plugins/rust/rust_utils.py, packages/rust/lsprotocol/Cargo.toml, packages/rust/lsprotocol/src/lib.rs
Hi! Currently all URI types are represented as `String`, which is very uncomfortable to work with. This pr 
- adds the `serde` feature to `url` crate in Cargo.toml
- adds `use url::Url;`
- changes the rust generator to generate `Url` instead of `String` for `DocumentUri` and `URI` types
This is similar to what [lsp-types](https://crates.io/crates/lsp-types) crate does.
Are there any disadvantages to doing so?
=> [rust] Consider using `url::Url` for `DocumentUri` and `URI` types

generator/lsp.json, packages/python/lsprotocol/types.py, packages/rust/lsprotocol/src/lib.rs, requirements.txt
Closes https://github.com/microsoft/lsprotocol/issues/386
=> Add support for TextDocumentContentResult

generator/__main__.py, generator/lsp.json, packages/python/lsprotocol/types.py, packages/python/pyproject.toml, packages/python/requirements.txt, packages/rust/lsprotocol/src/lib.rs, requirements.txt
Updates to latest LSP spec that contains CodeActionTag feature.
=> Code Action Tag for LLMs

README.md
Just created a [plugin](https://github.com/myleshyson/lsprotocol-go) for Golang and added it to the table in the readme.
=> Add golang to plugin table

RELEASE.md, packages/python/pyproject.toml
Updating `pyproject.toml` version in preparation for release.
=> Change `pyproject.toml` version to `2025.0.0rc1`

.vscode/launch.json, README.md
- Corrected section links in `README.md`
- Updated incorrect output of `python -m generator --help` in `README.md`
- Modified `.vscode/launch.json` to comply with the latest standards
=> Fix `README.md` links and output, update `.vscode/launch.json`
