generator/__main__.py, generator/lsp.json, generator/lsp.schema.json, generator/model.py, generator/requirements.txt, generator/utils.py, lsprotocol/types.py, pyproject.toml, tests/requirements.txt, tests/test_import.py
Closes https://github.com/microsoft/lsprotocol/issues/52
Closes https://github.com/microsoft/lsprotocol/issues/53
Closes https://github.com/microsoft/lsprotocol/issues/54
=> Fix missing types in code generation.

generator/lsp.json, generator/utils.py, lsprotocol/converters.py, lsprotocol/types.py, noxfile.py, tests/test_cattrs_special_cases.py
Closes https://github.com/microsoft/lsprotocol/issues/65
=> Update to latest LSP spec.

generator/requirements.txt, generator/utils.py, lsprotocol/types.py, noxfile.py, tests/requirements.txt, tests/test_location.py, tests/test_position.py, tests/test_range.py
Closes https://github.com/microsoft/lsprotocol/issues/60
=> Add comparison methods to few types.

generator/utils.py, lsprotocol/types.py
=> Ensure all mixin properties are included in the generated code.

lsprotocol/converters.py
Fixes https://github.com/microsoft/lsprotocol/issues/86
=> Add more cattrs hooks.

lsprotocol/_hooks.py, tests/test_cattrs_special_cases.py
Fixes https://github.com/microsoft/lsprotocol/issues/102
=> Add missing markup content hook.

lsprotocol/_hooks.py
spotted by mypy - which should encourage you to get this project mypy-clean and add it to the workflows
=> fix markup content hook

generator/utils.py, lsprotocol/_hooks.py, lsprotocol/types.py, tests/test_enums.py
=> Fix error with custom enum comparison and additional hooks

generator/utils.py, lsprotocol/types.py
Closes https://github.com/microsoft/lsprotocol/issues/120
=> Change `LSPObject` to be an alias of `object`

generator/utils.py, lsprotocol/_hooks.py, lsprotocol/types.py, noxfile.py, tests/test_cattrs_special_cases.py
=> Fix ParameterInformation

generator/utils.py, lsprotocol/types.py
Fixes https://github.com/microsoft/lsprotocol/issues/143
Fixes https://github.com/microsoft/lsprotocol/issues/136
=> Ensure LSPAny doesn't lead to recursive resolve.

.github/workflows/pr-check.yml, .prettierrc.js, .vscode/extensions.json
Fixes https://github.com/microsoft/lsprotocol/issues/152
=> Add `pygls` repository tests as smoke test

.github/workflows/lsp_updater.py
Fix for error:
```
Traceback (most recent call last):
File "/home/runner/work/lsprotocol/lsprotocol/./.github/workflows/lsp_updater.py", line 133, in <module>
main()
File "/home/runner/work/lsprotocol/lsprotocol/./.github/workflows/lsp_updater.py", line [12](https://github.com/microsoft/lsprotocol/actions/runs/4796214826/jobs/8531730896#step:5:13)0, in main
issue = GH_REPO.create_issue(
TypeError: Repository.create_issue() got an unexpected keyword argument 'state'
```
=> Fix LSP update detection GHA

generator/plugins/dotnet/custom/CustomArrayConverter.cs, generator/plugins/dotnet/custom/CustomObjectConverter.cs, generator/plugins/dotnet/custom/DocumentSelectorConverter.cs, generator/plugins/dotnet/custom/OrType.cs, generator/plugins/dotnet/custom/OrTypeArrayConverter.cs, generator/plugins/dotnet/custom/OrTypeConverter.cs, generator/plugins/dotnet/dotnet_classes.py, generator/plugins/dotnet/dotnet_helpers.py, tests/dotnet/lsprotocol_tests/LSPTests.cs
Fixes https://github.com/microsoft/lsprotocol/issues/254
=> Use ImmutableArray and ImmutableDictionary

generator/lsp.json, packages/python/lsprotocol/types.py, packages/python/pyproject.toml, packages/rust/lsprotocol/src/lib.rs
Fixes https://github.com/microsoft/lsprotocol/issues/274
=> Update to latest LSP spec

.vscode/settings.json, generator/plugins/python/utils.py, packages/python/lsprotocol/types.py
Fixes: https://github.com/microsoft/lsprotocol/issues/289
@alcarney: This PR adds the Result type. This feature will be available in 2024.0.0a1
=> Adds type alias for result types

packages/python/pyproject.toml, requirements.in
Closes #301.
Will resolve https://github.com/python-lsp/python-lsp-ruff/issues/61
=> Tighten cattrs dependency

.vscode/settings.json, packages/python/pyproject.toml
This is for a bug fix release to address a critical issue with one of the dependencies.
=> Update version to 2023.0.1

azure-pipelines/release-pypi.yml
Part of the API scan change for python packages
=> Add package name field to build pipelines

azure-pipelines/release-pypi.yml
The package is automatically published to artifacts in the publish step
=> Remove unnecessary publish step

generator/lsp.json, packages/python/lsprotocol/types.py, packages/rust/lsprotocol/src/lib.rs
fixes https://github.com/microsoft/lsprotocol/issues/405
=> Breaking change to `ApplyKind` from LSP Spec

packages/python/pyproject.toml
Updating `pyproject.toml` version in preparation for stable release.
=> Change `pyproject.toml` version to `2025.0.0`
